USE [OPEN_PRE]
GO
/****** Object:  Table [dbo].[MRO_MOTORACCION]    Script Date: 02/06/26 18:45:25 ******/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MRO_MOTORACCION](
	[MOTORACCION_ID] [int] NOT NULL,
	[ALTA_USR] [int] NULL,
	[ALTA_DT] [datetime] NULL,
	[MOD_USR] [int] NULL,
	[MOD_DT] [datetime] NULL,
	[TIPO_ACCION_CD] [varchar](20) NULL,
	[CAMPO_CD] [varchar](100) NULL,
	[VALOR_DS] [varchar](400) NULL,
	[TIPO_VALOR_CD] [varchar](20) NULL,
	[MOTORREGLA_ID] [int] NULL,
 CONSTRAINT [PK_MRO_MOTORACCION] PRIMARY KEY CLUSTERED 
(
	[MOTORACCION_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[MRO_MOTORCONDICION]    Script Date: 02/06/26 18:45:25 ******/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MRO_MOTORCONDICION](
	[MOTORCONDICION_ID] [int] NOT NULL,
	[ALTA_USR] [int] NULL,
	[ALTA_DT] [datetime] NULL,
	[MOD_USR] [int] NULL,
	[MOD_DT] [datetime] NULL,
	[GRUPO_CONDICION_CD] [varchar](20) NULL,
	[CAMPO_CD] [varchar](100) NULL,
	[TIPO_VALOR_CD] [varchar](20) NULL,
	[VALOR1_DS] [varchar](100) NULL,
	[VALOR2_DS] [varchar](100) NULL,
	[MOTORREGLA_ID] [int] NULL,
	[OPERADOR_CD] [varchar](20) NULL,
 CONSTRAINT [PK_MRO_MOTORCONDICION] PRIMARY KEY CLUSTERED 
(
	[MOTORCONDICION_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[MRO_MOTORCONDICIONVALOR]    Script Date: 02/06/26 18:45:25 ******/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MRO_MOTORCONDICIONVALOR](
	[MOTORCONDICIONVALOR_ID] [int] NOT NULL,
	[ALTA_USR] [int] NULL,
	[ALTA_DT] [datetime] NULL,
	[MOD_USR] [int] NULL,
	[MOD_DT] [datetime] NULL,
	[VALOR_DS] [varchar](100) NULL,
	[MOTORCONDICION_ID] [int] NULL,
 CONSTRAINT [PK_MRO_MOTORCONDICIONVALOR] PRIMARY KEY CLUSTERED 
(
	[MOTORCONDICIONVALOR_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[MRO_MOTORFECHA]    Script Date: 02/06/26 18:45:25 ******/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MRO_MOTORFECHA](
	[MOTORFECHA_ID] [int] NOT NULL,
	[MOTORFECHA_DS] [varchar](100) NULL,
	[ALTA_USR] [int] NULL,
	[ALTA_DT] [datetime] NULL,
	[MOD_USR] [int] NULL,
	[MOD_DT] [datetime] NULL,
	[DESDE_DT] [datetime] NULL,
	[HASTA_DT] [datetime] NULL,
	[TIPO_DS] [varchar](100) NULL,
	[BORRADO_FL] [bit] NULL,
	[BORRADO_USR] [int] NULL,
	[BORRADO_DT] [datetime] NULL,
 CONSTRAINT [PK_MRO_MOTORFECHA] PRIMARY KEY CLUSTERED 
(
	[MOTORFECHA_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[MRO_MOTORLOG]    Script Date: 02/06/26 18:45:25 ******/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MRO_MOTORLOG](
	[LOGMOTOR_ID] [int] NOT NULL,
	[ALTA_USR] [int] NULL,
	[ALTA_DT] [datetime] NULL,
	[EXPEDIENTE_ID] [varchar](20) NULL,
	[NUM_CLIENTE_CD] [varchar](20) NULL,
	[LOGMOTOR_XML] [nvarchar](max) NULL,
 CONSTRAINT [PK_MRO_MOTORLOG] PRIMARY KEY CLUSTERED 
(
	[LOGMOTOR_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[MRO_MOTOROFERTA]    Script Date: 02/06/26 18:45:25 ******/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MRO_MOTOROFERTA](
	[MOTOROFERTA_ID] [int] NOT NULL,
	[ALTA_USR] [int] NULL,
	[ALTA_DT] [datetime] NULL,
	[MOD_USR] [int] NULL,
	[MOD_DT] [datetime] NULL,
	[OFERTA_RANK_NM] [int] NULL,
	[VERSION_PUBLICADA_NM] [int] NULL,
	[BORRADO_FL] [bit] NULL,
	[BORRADO_USR] [int] NULL,
	[BORRADO_DT] [datetime] NULL,
	[OFERTA_ID] [int] NULL,
	[MOTOROFERTA_XML] [xml] NULL,
 CONSTRAINT [PK_MRO_MOTOROFERTA] PRIMARY KEY CLUSTERED 
(
	[MOTOROFERTA_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[MRO_MOTORPARAM]    Script Date: 02/06/26 18:45:25 ******/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MRO_MOTORPARAM](
	[MOTORPARAM_ID] [int] NOT NULL,
	[ALTA_USR] [int] NULL,
	[ALTA_DT] [datetime] NULL,
	[MOD_USR] [int] NULL,
	[MOD_DT] [datetime] NULL,
	[BORRADO_FL] [bit] NULL,
	[BORRADO_USR] [int] NULL,
	[BORRADO_DT] [datetime] NULL,
	[PARAM_KEY_CD] [varchar](100) NULL,
	[TIPO_VALOR_CD] [varchar](20) NULL,
	[VALOR_DS] [varchar](100) NULL,
	[BORRAR_VIGENCIA_DESDE_DT] [datetime] NULL,
	[BORRAR_VIGENCIA_HASTA_DT] [datetime] NULL,
	[MOTOROFERTA_ID] [int] NULL,
	[MOTORFECHA_ID] [int] NULL,
 CONSTRAINT [PK_MRO_MOTORPARAM] PRIMARY KEY CLUSTERED 
(
	[MOTORPARAM_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[MRO_MOTORREGLA]    Script Date: 02/06/26 18:45:25 ******/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MRO_MOTORREGLA](
	[MOTORREGLA_ID] [int] NOT NULL,
	[MOTORREGLA_DS] [varchar](100) NULL,
	[ALTA_USR] [int] NULL,
	[ALTA_DT] [datetime] NULL,
	[MOD_USR] [int] NULL,
	[MOD_DT] [datetime] NULL,
	[PRIORIDAD_NM] [int] NULL,
	[PARAR_PROCESO_FL] [bit] NULL,
	[BORRAR_VIGENCIA_DESDE_DT] [datetime] NULL,
	[BORRAR_VIGENCIA_HASTA_DT] [datetime] NULL,
	[MOTOROFERTA_ID] [int] NULL,
	[BORRADO_FL] [bit] NULL,
	[BORRADO_USR] [int] NULL,
	[BORRADO_DT] [datetime] NULL,
	[MOTORFECHA_ID] [int] NULL,
 CONSTRAINT [PK_MRO_MOTORREGLA] PRIMARY KEY CLUSTERED 
(
	[MOTORREGLA_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[MRO_MOTORSNAPSHOT]    Script Date: 02/06/26 18:45:25 ******/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MRO_MOTORSNAPSHOT](
	[MOTORSNAPSHOT_ID] [int] NOT NULL,
	[ALTA_USR] [int] NULL,
	[ALTA_DT] [datetime] NULL,
	[MOD_USR] [int] NULL,
	[MOD_DT] [datetime] NULL,
	[NOMBRE_DS] [varchar](100) NULL,
	[COMENTARIO_DS] [varchar](100) NULL,
	[ENTORNO_CD] [varchar](20) NULL,
	[REGLAS_JSON] [nvarchar](max) NULL,
	[PARAMETROS_JSON] [nvarchar](max) NULL,
 CONSTRAINT [PK_MRO_MOTORSNAPSHOT] PRIMARY KEY CLUSTERED 
(
	[MOTORSNAPSHOT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[MRO_MOTORACCION]  WITH CHECK ADD  CONSTRAINT [FK_MRO_MOTORA_MOTORREGLA_ID] FOREIGN KEY([MOTORREGLA_ID])
REFERENCES [dbo].[MRO_MOTORREGLA] ([MOTORREGLA_ID])
GO
ALTER TABLE [dbo].[MRO_MOTORACCION] CHECK CONSTRAINT [FK_MRO_MOTORA_MOTORREGLA_ID]
GO
ALTER TABLE [dbo].[MRO_MOTORCONDICION]  WITH CHECK ADD  CONSTRAINT [FK_MRO_MOTORC_MOTORREGLA_ID] FOREIGN KEY([MOTORREGLA_ID])
REFERENCES [dbo].[MRO_MOTORREGLA] ([MOTORREGLA_ID])
GO
ALTER TABLE [dbo].[MRO_MOTORCONDICION] CHECK CONSTRAINT [FK_MRO_MOTORC_MOTORREGLA_ID]
GO
ALTER TABLE [dbo].[MRO_MOTORCONDICIONVALOR]  WITH CHECK ADD  CONSTRAINT [FK_MRO_MOTORC_MOTORCONDICION_I] FOREIGN KEY([MOTORCONDICION_ID])
REFERENCES [dbo].[MRO_MOTORCONDICION] ([MOTORCONDICION_ID])
GO
ALTER TABLE [dbo].[MRO_MOTORCONDICIONVALOR] CHECK CONSTRAINT [FK_MRO_MOTORC_MOTORCONDICION_I]
GO
ALTER TABLE [dbo].[MRO_MOTORFECHA]  WITH CHECK ADD  CONSTRAINT [FK_MRO_MOTORFECHA_BORRADO_USR] FOREIGN KEY([BORRADO_USR])
REFERENCES [dbo].[AD_USR] ([USR_CD])
GO
ALTER TABLE [dbo].[MRO_MOTORFECHA] CHECK CONSTRAINT [FK_MRO_MOTORFECHA_BORRADO_USR]
GO
ALTER TABLE [dbo].[MRO_MOTOROFERTA]  WITH CHECK ADD  CONSTRAINT [FK_MRO_MOTOROFERTA_BORRADO_USR] FOREIGN KEY([BORRADO_USR])
REFERENCES [dbo].[AD_USR] ([USR_CD])
GO
ALTER TABLE [dbo].[MRO_MOTOROFERTA] CHECK CONSTRAINT [FK_MRO_MOTOROFERTA_BORRADO_USR]
GO
ALTER TABLE [dbo].[MRO_MOTOROFERTA]  WITH CHECK ADD  CONSTRAINT [FK_MRO_MOTOROFERTA_OFERTA2_ID] FOREIGN KEY([OFERTA_ID])
REFERENCES [dbo].[HIPO_OFERTA] ([OFERTA_ID])
GO
ALTER TABLE [dbo].[MRO_MOTOROFERTA] CHECK CONSTRAINT [FK_MRO_MOTOROFERTA_OFERTA2_ID]
GO
ALTER TABLE [dbo].[MRO_MOTORPARAM]  WITH CHECK ADD  CONSTRAINT [FK_MRO_MOTORP_MOTORFECHA_ID] FOREIGN KEY([MOTORFECHA_ID])
REFERENCES [dbo].[MRO_MOTORFECHA] ([MOTORFECHA_ID])
GO
ALTER TABLE [dbo].[MRO_MOTORPARAM] CHECK CONSTRAINT [FK_MRO_MOTORP_MOTORFECHA_ID]
GO
ALTER TABLE [dbo].[MRO_MOTORPARAM]  WITH CHECK ADD  CONSTRAINT [FK_MRO_MOTORP_MOTOROFERTA_ID] FOREIGN KEY([MOTOROFERTA_ID])
REFERENCES [dbo].[MRO_MOTOROFERTA] ([MOTOROFERTA_ID])
GO
ALTER TABLE [dbo].[MRO_MOTORPARAM] CHECK CONSTRAINT [FK_MRO_MOTORP_MOTOROFERTA_ID]
GO
ALTER TABLE [dbo].[MRO_MOTORPARAM]  WITH CHECK ADD  CONSTRAINT [FK_MRO_MOTORPARAM_BORRADO_USR] FOREIGN KEY([BORRADO_USR])
REFERENCES [dbo].[AD_USR] ([USR_CD])
GO
ALTER TABLE [dbo].[MRO_MOTORPARAM] CHECK CONSTRAINT [FK_MRO_MOTORPARAM_BORRADO_USR]
GO
ALTER TABLE [dbo].[MRO_MOTORREGLA]  WITH CHECK ADD  CONSTRAINT [FK_MRO_MOTORR_MOTORFECHA_ID] FOREIGN KEY([MOTORFECHA_ID])
REFERENCES [dbo].[MRO_MOTORFECHA] ([MOTORFECHA_ID])
GO
ALTER TABLE [dbo].[MRO_MOTORREGLA] CHECK CONSTRAINT [FK_MRO_MOTORR_MOTORFECHA_ID]
GO
ALTER TABLE [dbo].[MRO_MOTORREGLA]  WITH CHECK ADD  CONSTRAINT [FK_MRO_MOTORR_MOTOROFERTA_ID] FOREIGN KEY([MOTOROFERTA_ID])
REFERENCES [dbo].[MRO_MOTOROFERTA] ([MOTOROFERTA_ID])
GO
ALTER TABLE [dbo].[MRO_MOTORREGLA] CHECK CONSTRAINT [FK_MRO_MOTORR_MOTOROFERTA_ID]
GO
ALTER TABLE [dbo].[MRO_MOTORREGLA]  WITH CHECK ADD  CONSTRAINT [FK_MRO_MOTORREGLA_BORRADO_USR] FOREIGN KEY([BORRADO_USR])
REFERENCES [dbo].[AD_USR] ([USR_CD])
GO
ALTER TABLE [dbo].[MRO_MOTORREGLA] CHECK CONSTRAINT [FK_MRO_MOTORREGLA_BORRADO_USR]
GO
