DECLARE @VF DATE = '2026-01-01';

truncate table dbo.cfg_offer_param 
-- Restrictiva
INSERT INTO dbo.cfg_offer_param (ruleset_id, stage, param_key, value_type, value, valid_from, valid_to, enabled)
VALUES
(1,'FINAL','MAX_LTV','NUMBER','0.80',@VF,NULL,1),
(1,'PRE',  'MIN_HIPOTECA','NUMBER','50000',@VF,NULL,1),
(1,'PRE',  'MAX_HIPOTECA','NUMBER','300000',@VF,NULL,1),
(1,'PRE',  'MIN_PLAZO_MESES','NUMBER','60',@VF,NULL,1),
(1,'PRE',  'MAX_PLAZO_MESES','NUMBER','360',@VF,NULL,1),
(1,'PRE',  'REQUIERE_PRIMERA_VIVIENDA','BOOL','true',@VF,NULL,1),
(1,'PRE',  'MAX_EDAD','NUMBER','35',@VF,NULL,1),
(1,'PRE',  'MIN_INGRESOS_1T','NUMBER','20000',@VF,NULL,1),
(1,'PRE',  'MIN_INGRESOS_2T','NUMBER','30000',@VF,NULL,1),

-- Permisiva
(2,'PRE','TIPO_ALTA_ADMITIDAS','JSON','["CAPTACION","NOVACION"]',@VF,NULL,1),
(2,'FINAL','MIN_LTV_EXCLUSIVE','NUMBER','0.80',@VF,NULL,1),
(2,'FINAL','MAX_LTV','NUMBER','0.95',@VF,NULL,1),
(2,'PRE',  'MIN_HIPOTECA','NUMBER','30000',@VF,NULL,1),
(2,'PRE',  'MAX_HIPOTECA','NUMBER','400000',@VF,NULL,1),
(2,'PRE',  'MIN_PLAZO_MESES','NUMBER','60',@VF,NULL,1),
(2,'PRE',  'MAX_PLAZO_MESES','NUMBER','480',@VF,NULL,1),
(2,'PRE',  'REQUIERE_PRIMERA_VIVIENDA','BOOL','false',@VF,NULL,1),
(2,'PRE',  'MAX_EDAD','NUMBER','40',@VF,NULL,1),
(2,'PRE',  'MIN_INGRESOS_2T','NUMBER','22000',@VF,NULL,1);
